# Generated by Django 3.1.3 on 2020-11-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=60)),
                ('image_caption', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('profile_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaapp.profile')),
            ],
        ),
    ]
