# Generated by Django 3.1.3 on 2020-11-22 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0003_auto_20201122_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pics', upload_to='uploads/'),
        ),
    ]
