# Generated by Django 3.1.3 on 2020-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0009_auto_20201123_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('image_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='uploads/harp_b1l0RNq.jpeg', upload_to='uploads/'),
        ),
    ]
