# Generated by Django 3.1.3 on 2020-11-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0010_auto_20201127_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='image_id',
            new_name='an_image_id',
        ),
    ]
